#!/usr/bin/env python3
"""Subset Liberation Sans (Regular+Bold) to the glyphs needed for Croatian PDF export,
then emit a TS module with base64 font data for jsPDF."""
import base64, io, os
from fontTools import subset

SRC_DIR = "/usr/share/fonts/truetype/liberation"
OUT_TS = "/home/user/workspace/ribolov/src/pdfFont.ts"

# Characters we need: ASCII printable + Croatian diacritics + common punctuation
chars = set()
for c in range(0x20, 0x7F):
    chars.add(chr(c))
# Croatian Latin Extended-A
for ch in "čćđšžČĆĐŠŽ":
    chars.add(ch)
# Misc punctuation used in app
for ch in "—–„""''…·°":
    chars.add(ch)
unicodes = sorted(ord(c) for c in chars)

def subset_font(path):
    opts = subset.Options()
    opts.layout_features = ["*"]
    opts.name_IDs = ["*"]
    opts.notdef_outline = True
    opts.recalc_bounds = True
    opts.drop_tables = []
    font = subset.load_font(path, opts)
    subsetter = subset.Subsetter(options=opts)
    subsetter.populate(unicodes=unicodes)
    subsetter.subset(font)
    buf = io.BytesIO()
    subset.save_font(font, buf, opts)
    return buf.getvalue()

reg = subset_font(os.path.join(SRC_DIR, "LiberationSans-Regular.ttf"))
bold = subset_font(os.path.join(SRC_DIR, "LiberationSans-Bold.ttf"))
print("Regular subset:", len(reg), "bytes; Bold subset:", len(bold), "bytes")

reg_b64 = base64.b64encode(reg).decode("ascii")
bold_b64 = base64.b64encode(bold).decode("ascii")

with open(OUT_TS, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by scripts/subset_font.py — do not edit by hand.\n")
    f.write("// Liberation Sans (Regular + Bold), subset to ASCII + Croatian diacritics.\n")
    f.write("// Embedded so jsPDF can render č/ć/đ/š/ž correctly in native PDF output.\n")
    f.write(f'export const LIBERATION_SANS_REGULAR_B64 = "{reg_b64}";\n')
    f.write(f'export const LIBERATION_SANS_BOLD_B64 = "{bold_b64}";\n')
print("Wrote", OUT_TS)
